import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"
import betterTailwindcss from "eslint-plugin-better-tailwindcss"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build artefacts and vendored deps: linting them reports on generated
    // code nobody edits.
    "packages/*/dist/**",
    "packages/*/node_modules/**",
    "mcp-server/node_modules/**",
  ]),
  {
    // Tailwind lockdown, second half: app/globals.css removes the default
    // colours, radii and shadows, so bg-red-500 generates no CSS; this makes
    // the same class an error before it ships. Unknown = not generated by the
    // real stylesheet, design-system tokens included.
    files: ["{app,components,lib,hooks}/**/*.{ts,tsx}"],
    plugins: { "better-tailwindcss": betterTailwindcss },
    settings: { "better-tailwindcss": { entryPoint: "app/globals.css" } },
    rules: {
      "better-tailwindcss/no-unknown-classes": [
        "error",
        {
          // Hooks, not utilities: sonner styles `.toaster`, and shadcn's
          // input-otp targets `.cn-input-otp` from its own stylesheet.
          ignore: ["^toaster$", "^cn-input-otp$"],
        },
      ],
    },
  },
  {
    // CommonJS tooling scripts: require() is the correct syntax there.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
])

export default eslintConfig
