import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"
import betterTailwindcss from "eslint-plugin-better-tailwindcss"
import { createRequire } from "node:module"

// eslint-plugin-react 7.37 detects the React version through
// context.getFilename(), which ESLint 10 removed: `version: "detect"` crashes
// every react/* rule. Reading the installed version gives the same answer
// without the removed API.
const reactVersion = createRequire(import.meta.url)(
  "react/package.json"
).version

// A class assembled at runtime (`[&>*]:${color}`) is never generated: Tailwind
// reads the source as text and only sees complete class names. Interpolation
// in a class string is allowed between whole classes (`px-2 ${FOCUS_RING}`),
// never glued to a fragment of one. Pick the class from a static table instead.
const CLASS_CONTEXT =
  ":matches(JSXAttribute[name.name=/^className$|ClassName$/], CallExpression[callee.name=/^(cn|cva)$/])"
const CLASS_INTERPOLATION = [
  `${CLASS_CONTEXT} TemplateLiteral > TemplateElement[tail=false][value.raw=/\\S$/]`,
  `${CLASS_CONTEXT} TemplateLiteral > TemplateElement:not(:first-child)[value.raw=/^\\S/]`,
].map((selector) => ({
  selector,
  message:
    "A class built by interpolation is never generated by Tailwind: pick the complete class name from a static table.",
}))

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  { settings: { react: { version: reactVersion } } },
  // The rule looks for a pages/ directory: the documentation site (site/) uses
  // the App Router only, so it has no page to link to and only warns that it
  // cannot find one.
  { rules: { "@next/next/no-html-link-for-pages": "off" } },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The documentation site's build output and generated types.
    "site/.next/**",
    "site/out/**",
    "site/next-env.d.ts",
    // The specs' code examples, copied as written by
    // scripts/build-site-examples.ts: npm run site:check lints them with the
    // config a consuming project runs, as the specs are linted.
    "site/generated/**",
    // Build artefacts and vendored deps: linting them reports on generated
    // code nobody edits.
    "packages/*/dist/**",
    "packages/*/node_modules/**",
    "mcp-server/node_modules/**",
    // The retokenized upstream components of `npm run shadcn:drift`, for review.
    ".shadcn-vanilla/**",
    // The harness's screens: generated (.work) or wrong on purpose (fixtures).
    "evals/.work/**",
    "evals/fixtures/**",
  ]),
  {
    // Tailwind lockdown, second half: styles/globals.css removes the default
    // colors, radii and shadows, so bg-red-500 generates no CSS; this makes
    // the same class an error before it ships. Unknown = not generated by the
    // real stylesheet, design-system tokens included.
    files: ["{components,lib,hooks,site}/**/*.{ts,tsx}"],
    plugins: { "better-tailwindcss": betterTailwindcss },
    settings: { "better-tailwindcss": { entryPoint: "styles/globals.css" } },
    rules: {
      "better-tailwindcss/no-unknown-classes": [
        "error",
        {
          // A hook, not a utility: sonner styles `.toaster`.
          ignore: ["^toaster$"],
        },
      ],
      // A disabled state reads opacity.disabled, not Tailwind's opacity
      // scale: `disabled:opacity-50` would keep the look and drop the token.
      "better-tailwindcss/no-restricted-classes": [
        "error",
        {
          restrict: [
            {
              pattern: "^(.*disabled[^:]*:)opacity-\\d+$",
              message:
                "A disabled state uses the opacity.disabled token: write $1opacity-disabled.",
              fix: "$1opacity-disabled",
            },
            // specs/foundations/opacity.md: opacity is for binary states. What
            // is left once disabled is handled: show / hide (0, 100). A
            // placeholder is colored (placeholder:text-muted-foreground) and a
            // modal backdrop is a tint (bg-black/10), so neither needs one.
            // Dimming a text or an icon is a color token's job.
            {
              pattern:
                "^(?!(?:.*:)?opacity-(?:0|100|disabled)$).*opacity-\\d+$",
              message:
                "Opacity is for binary states (specs/foundations/opacity.md): show / hide with opacity-0 and opacity-100, or a color token such as text-muted-foreground to dim a text or an icon.",
            },
          ],
        },
      ],
    },
  },
  {
    // AGENTS.md § 1 — Phosphor icons only. A second kit is not a style choice:
    // its icons have other sizes and strokes, and agents copy what they see.
    files: ["{components,lib,hooks,site}/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "lucide-react",
                "lucide-react/*",
                "@heroicons/*",
                "react-icons",
                "react-icons/*",
                "@radix-ui/react-icons",
                "@tabler/icons-react",
                "react-feather",
                "@fortawesome/*",
                "@mui/icons-material",
                "@mui/icons-material/*",
                "iconoir-react",
                "@iconify/*",
              ],
              message:
                "Icons come from @phosphor-icons/react only (AGENTS.md § 1).",
            },
          ],
        },
      ],
      // No inline SVG either: an icon drawn by hand is an icon outside the kit.
      "no-restricted-syntax": [
        "error",
        {
          selector: "JSXOpeningElement[name.name='svg']",
          message:
            "No inline SVG (AGENTS.md § 1): use an icon from @phosphor-icons/react.",
        },
        ...CLASS_INTERPOLATION,
      ],
    },
  },
  {
    // Declared exceptions to the inline SVG rule: artwork, not icons. The
    // brand mark and the placeholder illustration have no Phosphor equivalent.
    files: ["components/ui/logo.tsx", "components/ui/illustration.tsx"],
    rules: { "no-restricted-syntax": ["error", ...CLASS_INTERPOLATION] },
  },
  {
    // CommonJS tooling scripts: require() is the correct syntax there.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
])

export default eslintConfig
