/**
 * Terrazzo — DTCG 2025.10 conformance of tokens/*.json (`npm run tokens:lint-dtcg`).
 *
 * The input is the resolver: it merges the three tiers into one DTCG document,
 * so a semantic token names its primitive in full, `{primitive.radius.md}`,
 * then applies the light or dark context. scripts/lint-dtcg.ts checks every
 * permutation; tokens.css stays generated by scripts/build-tokens.ts.
 */
import { defineConfig } from "@terrazzo/cli"

export default defineConfig({
  tokens: ["./tokens/tokens.resolver.json"],
  outDir: "./node_modules/.cache/terrazzo/",
  lint: {
    rules: {
      "core/valid-color": "error",
      "core/valid-dimension": [
        "error",
        // Declared divergence: DTCG 2025.10 allows px and rem only. Letter
        // spacing stays in em so tracking scales with the font size it sets.
        { allowedUnits: ["px", "rem", "em"] },
      ],
      "core/valid-font-family": "error",
      "core/valid-font-weight": "error",
      "core/valid-duration": "error",
      "core/valid-cubic-bezier": "error",
      "core/valid-number": "error",
      "core/valid-shadow": "error",
      "core/colorspace": ["error", { colorSpace: "srgb" }],
      "core/required-type": "error",
      "core/descriptions": "error",
      "core/consistent-naming": ["error", { format: "kebab-case" }],
    },
  },
})
