import { listFiles, readText } from "@/site/lib/repo"

const DIR = "site/generated/examples/foundations"

/** The foundations' live examples, by key: `motion-1`, `typography-2`. */
export function foundationExampleKeys(): string[] {
  return listFiles(DIR, ".tsx").map((file) => file.replace(/\.tsx$/, ""))
}

/** A foundation example's code, as the spec writes it (the generated header and directive removed). */
export function foundationExampleCode(key: string): string {
  return readText(`${DIR}/${key}.tsx`)
    .replace(/^\/\/ Generated by [^\n]*\n/, "")
    .replace(/^"use client"\n+/, "")
}
