import type { TSESTree } from "@typescript-eslint/utils"
import { createRule } from "./utils.js"

/**
 * A class assembled at runtime (`[&>*]:${color}`) is never generated: Tailwind
 * reads the source as text and only sees complete class names. Interpolation
 * between whole classes (`px-2 ${FOCUS_RING}`) is fine, never glued to a
 * fragment of one.
 */
const CLASS_CONTEXT =
  ":matches(JSXAttribute[name.name=/^className$|ClassName$/], CallExpression[callee.name=/^(cn|cva|clsx|twMerge|tv)$/])"

export default createRule({
  name: "no-class-interpolation",
  meta: {
    type: "problem",
    docs: {
      description:
        "Forbid a Tailwind class built by interpolation: Tailwind never generates it",
    },
    messages: {
      interpolation:
        "A class built by interpolation is never generated by Tailwind: pick the complete class name from a static table.",
    },
    schema: [],
  },
  defaultOptions: [],
  create(context) {
    const report = (node: TSESTree.TemplateElement) =>
      context.report({ node, messageId: "interpolation" })
    return {
      [`${CLASS_CONTEXT} TemplateLiteral > TemplateElement[tail=false][value.raw=/\\S$/]`]:
        report,
      [`${CLASS_CONTEXT} TemplateLiteral > TemplateElement:not(:first-child)[value.raw=/^\\S/]`]:
        report,
    }
  },
})
