/**
 * Writes the `## States` section of every component spec from the classes of
 * the component's code.
 *
 * Written by hand, the table had drifted: Button's hover claimed "90 %
 * opacity" where the code draws `hover:bg-primary/80`, Slider's ring was
 * "1px" where the code draws `--space-focus-ring-width`, ten overlays entered
 * with `fade-in` where the code has `fade-in-0`. The code now decides which
 * states a component draws and the classes that draw each one; people write
 * the descriptions, which are read back from the spec and kept.
 *
 * - Each class of the component's file, and of the `@/lib/*` constants it
 *   imports (scripts/lib/spec-classes.ts), goes under the state its variants
 *   name: `hover:`, `focus-visible:`, `data-open:`, `aria-invalid:`… (STATES).
 *   A class that stacks two states (`data-open:hover:`) is listed under both,
 *   as written. Layout variants (`dark:`, `sm:`, `data-[size=sm]:`, `*:`)
 *   name no state (LAYOUT). A variant in neither table fails the run, so a new
 *   one is classified, never dropped.
 * - A row is kept from the spec by its state, with its description. A state
 *   the code draws and the spec does not describe gets `_To document._`, and
 *   the run fails until it is written. A row the code has no class for
 *   (`default`, `loading`) stays, with `—`.
 * - A description is rejected when the Classes column can contradict it: a
 *   percentage or a px value, or a class the component does not draw — the
 *   row's own classes and the component's stateless ones are the ones it may
 *   name. That is how Button's "90 %" was born.
 *
 *   npx tsx scripts/build-spec-states.ts [--check] [Spec…]
 *
 * Spec names (`Button Dialog`) limit the run to those specs.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { resolve, dirname, basename } from "node:path"
import { fileURLToPath } from "node:url"
import { format, resolveConfig } from "prettier"
import {
  classResolver,
  codePathsOf,
  composedOf,
  stringsOf,
  utilityOf,
  variantsOf,
} from "./lib/spec-classes.js"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const CHECK = process.argv.includes("--check")
const ONLY = new Set(process.argv.slice(2).filter((a) => !a.startsWith("--")))
const SPECS_DIR = resolve(ROOT, "specs/components")
const HEADING = "## States"
const START =
  "<!-- Generated by scripts/build-spec-states.ts from the component's classes. Only the descriptions are edited by hand; they are kept. -->"
const END = "<!-- End of the generated part. -->"
const PLACEHOLDER = "_To document._"

// ---------------------------------------------------------------------------
// Which state a variant names
// ---------------------------------------------------------------------------

/**
 * The states, in the order their rows are written, and the variants that
 * name each one. A variant is matched once `group-` or `peer-` (and its
 * `/name`) and `has-` are taken off: `group-data-[disabled=true]/field` and
 * `has-disabled` name `disabled`, like `disabled` itself.
 */
const STATES: [string, RegExp][] = [
  ["hover", /^hover$/],
  ["focus", /^(?:focus|focus-visible|focus-within)$|^data-\[focused=true\]$/],
  ["active", /^(?:active|data-active)$|^data-\[active=true\]$/],
  ["pressed", /^(?:aria-pressed|data-pressed)$|^data-\[state=on\]$/],
  [
    "selected",
    /^(?:aria-selected|data-selected)$|^data-\[(?:selected|selected-single|range-start|range-middle|range-end)=true\]$|^data-\[state=selected\]$/,
  ],
  [
    "checked",
    /^(?:checked|aria-checked|data-checked)$|^data-\[checked=true\]$|^data-\[state=checked\]$/,
  ],
  ["unchecked", /^data-unchecked$|^data-\[state=unchecked\]$/],
  ["highlighted", /^data-highlighted$/],
  [
    "open",
    /^(?:open|aria-expanded|data-open|data-popup-open)$|^data-\[state=(?:open|delayed-open|instant-open|visible|expanded)\]$/,
  ],
  ["closing", /^data-closed$|^data-\[state=(?:closed|hidden)\]$/],
  [
    "collapsed",
    /^data-\[state=collapsed\]$|^data-\[collapsible=(?:icon|offcanvas)\]$/,
  ],
  [
    "disabled",
    /^(?:disabled|aria-disabled|data-disabled)$|^data-\[disabled=true\]$/,
  ],
  [
    "error",
    /^(?:invalid|aria-invalid|data-invalid)$|^data-\[invalid=true\]$|^data-\[state=error\]$/,
  ],
  ["placeholder", /^(?:placeholder|placeholder-shown|data-placeholder)$/],
  ["empty", /^data-empty$/],
  ["pending", /^data-pending-scroll$/],
]
const ORDER = ["default", ...STATES.map(([state]) => state)]

/** What an arbitrary selector (`[&:hover]`, `has-[:focus-visible]`) tests, by state. */
const SELECTOR_STATES: [string, RegExp][] = [
  ["hover", /:hover\b/],
  ["focus", /:focus(?:-visible|-within)?\b|\[data-focused=true\]/],
  ["active", /:active\b|\[data-active(?:=true)?\]/],
  ["selected", /\[data-selected=true\]|\[aria-selected=true\]/],
  ["checked", /:checked\b|\[data-checked\]|\[data-state=checked\]/],
  ["open", /\[aria-expanded=true\]|\[data-state=open\]|\[data-open\]/],
  [
    "collapsed",
    /\[data-state=collapsed\]|\[data-collapsible=(?:icon|offcanvas)\]/,
  ],
  [
    "disabled",
    /:disabled\b|\[data-disabled(?:=true)?\]|\[aria-disabled=true\]/,
  ],
  ["error", /\[aria-invalid(?:=true)?\]/],
]

/** Variants that name no state: themes, breakpoints, pseudo-elements, structure, a component's variant or slot. */
const LAYOUT: RegExp[] = [
  /^(?:dark|light|rtl|ltr|print|forced-colors|motion-safe|motion-reduce|portrait|landscape|contrast-more|contrast-less)$/,
  /^(?:sm|md|lg|xl|2xl|max-sm|max-md|max-lg|max-xl|max-2xl|min-\[[^\]]+\]|max-\[[^\]]+\])$/,
  /^@[\w-]*(?:\/[\w-]+)?$|^@\[[^\]]+\](?:\/[\w-]+)?$/,
  /^supports-[\w-]+$|^supports-\[[^\]]+\]$/,
  /^(?:after|before|file|selection|marker|backdrop|first-letter|first-line)$/,
  /^(?:\*|\*\*|first|last|only|odd|even|first-of-type|last-of-type|only-of-type|nth-[\w-]+|nth-\[[^\]]+\]|nth-last-[\w-]+|nth-last-\[[^\]]+\])$/,
  /^(?:data|aria)-\[(?:slot|size|side|variant|orientation|align|align-trigger|spacing|direction|position|vaul-drawer-direction|motion|chips|viewport|type|shortcut|icon|sidebar|inset|level|sizing|haspopup|panel-group-direction|swipe|swipe-direction|starting-style|ending-style|separator|sorted|layout|mobile|nav|disabled=false|active=false|selected=false|state=inactive)(?:\^?=[^\]]*)?\]$/,
  /^data-(?:slot|vertical|horizontal|inset|side|align|orientation|starting-style|ending-style)$/,
  /^aria-(?:haspopup|orientation)$/,
]

/** Any `data-[state=…]` value the tables above do not name is a state of its own (Attachment's `uploading`, `done`). */
const DATA_STATE = /^data-\[state=([\w-]+)\]$/

const unclassified = new Set<string>()

/** The states a variant names; none for a layout variant, a negation or a context. */
function statesOf(variant: string, file: string): string[] {
  let v = variant.replace(/^(?:group|peer)-/, "").replace(/\/[\w-]+$/, "")
  if (/^(?:not|in)-/.test(v)) return []
  if (v.startsWith("has-")) v = v.slice("has-".length)
  if (v.startsWith("[") || v.startsWith("&")) {
    return SELECTOR_STATES.filter(([, re]) => re.test(v)).map(([s]) => s)
  }
  const states = STATES.filter(([, re]) => re.test(v)).map(([s]) => s)
  if (states.length > 0) return states
  const dataState = DATA_STATE.exec(v)?.[1]
  if (dataState) return [dataState]
  if (LAYOUT.some((re) => re.test(v))) return []
  unclassified.add(`${variant} (${file})`)
  return []
}

// ---------------------------------------------------------------------------
// The classes of a component, by state
// ---------------------------------------------------------------------------
const cssOf = await classResolver(ROOT)

interface Classes {
  /** state → the classes that draw it, as written. */
  byState: Map<string, Set<string>>
  /** The classes with no state variant: the component at rest. */
  base: Set<string>
}

async function classesOf(codePath: string): Promise<Classes> {
  const byState = new Map<string, Set<string>>()
  const base = new Set<string>()
  for (const { text } of await stringsOf(ROOT, codePath)) {
    const candidates = text.split(/\s+/).filter(Boolean)
    cssOf(candidates).forEach((css, i) => {
      if (!css) return
      const candidate = candidates[i]
      const states = new Set(
        variantsOf(candidate).flatMap((v) => statesOf(v, codePath))
      )
      if (states.size === 0) base.add(candidate)
      for (const state of states) {
        const set = byState.get(state) ?? new Set()
        set.add(candidate)
        byState.set(state, set)
      }
    })
  }
  return { byState, base }
}

// ---------------------------------------------------------------------------
// What the spec already says
// ---------------------------------------------------------------------------
const code = (s: string) => `\`${s.replace(/\|/g, "\\|")}\``
const cells = (line: string) =>
  line
    .trim()
    .replace(/^\||\|$/g, "")
    .split(/(?<!\\)\|/)
    .map((c) => c.trim())
/** A row's key: its state, without backticks, in lower case. */
const keyOf = (cell: string) => cell.replace(/`/g, "").trim().toLowerCase()

interface Existing {
  /** state → description, in the order written. */
  rows: Map<string, string>
  /** What follows the generated part, kept as written. */
  tail: string
}

function readExisting(section: string, spec: string): Existing {
  const generated = section.includes(END)
  const body = generated ? section.split(END)[0] : section
  const tail = generated ? section.split(END)[1].trim() : ""
  const lines = body.split("\n")
  const at = lines.findIndex((l) => l.startsWith("|"))
  const rows = new Map<string, string>()
  if (at === -1) return { rows, tail }
  const header = cells(lines[at]).map((h) => h.toLowerCase())
  const desc = header.findIndex((h) =>
    ["description", "visual behavior"].includes(h)
  )
  if (desc === -1)
    throw new Error(`${spec}: the States table has no Description column`)
  for (const line of lines.slice(at + 2)) {
    if (!line.startsWith("|")) break
    const c = cells(line)
    const key = keyOf(c[0])
    const written = c[desc] ?? ""
    const before = rows.get(key)
    if (before !== undefined && before !== PLACEHOLDER)
      throw new Error(`${spec}: the States table has two "${key}" rows`)
    rows.set(key, written)
  }
  if (!generated) {
    const rest = lines
      .slice(at + 2)
      .filter((l) => !l.startsWith("|"))
      .join("\n")
      .trim()
    if (rest) throw new Error(`${spec}: prose after the States table`)
  }
  return { rows, tail }
}

// ---------------------------------------------------------------------------
// Descriptions the Classes column contradicts
// ---------------------------------------------------------------------------
const COLOR_NAMES = new Set(
  [
    ...readFileSync(resolve(ROOT, "styles/globals.css"), "utf-8").matchAll(
      /--color-([a-z0-9-]+):/g
    ),
  ].map(([, name]) => name)
)
const PX_OR_PERCENT = /\d\s*(?:%|px\b)/

/** Why a description cannot stand next to the classes it may name; empty when it can. */
function problemsOf(description: string, allowed: Set<string>): string[] {
  const problems: string[] = []
  const utilities = new Set([...allowed].map(utilityOf))
  if (PX_OR_PERCENT.test(description.replace(/`[^`]*`/g, " ")))
    problems.push(
      "states a percentage or a px value: name the class or the token"
    )
  for (const [, span] of description.matchAll(/`([^`]+)`/g)) {
    for (const word of span.split(/\s+/).filter(Boolean)) {
      const isClass =
        /[-:/[(]/.test(word) &&
        !word.startsWith("--") &&
        !COLOR_NAMES.has(word) &&
        cssOf([word])[0] !== null
      if (!isClass) {
        if (!word.startsWith("--") && PX_OR_PERCENT.test(word))
          problems.push(
            `\`${word}\` is a raw value: name the class or the token`
          )
        continue
      }
      if (!allowed.has(word) && !utilities.has(word))
        problems.push(`names \`${word}\`, which the component does not draw`)
    }
  }
  return problems
}

// ---------------------------------------------------------------------------
// Section
// ---------------------------------------------------------------------------
const rejected: string[] = []
const undocumented: string[] = []

async function sectionFor(
  spec: string,
  codePath: string,
  section: string,
  specOf: Map<string, string>
): Promise<string> {
  const { byState, base } = await classesOf(codePath)
  const { rows: written, tail } = readExisting(section, spec)

  const drawn = (state: string) => byState.get(state) ?? new Set<string>()
  const states = [
    ...ORDER.filter((s) => s === "default" || byState.has(s) || written.has(s)),
    ...[...byState.keys()].filter((s) => !ORDER.includes(s)),
    ...[...written.keys()].filter((s) => !ORDER.includes(s) && !byState.has(s)),
  ]

  const lines = [
    HEADING,
    "",
    START,
    "",
    "| State | Classes | Description |",
    "|---|---|---|",
  ]
  for (const state of states) {
    const classes = drawn(state)
    const description = written.get(state) || PLACEHOLDER
    if (description === PLACEHOLDER) undocumented.push(`${spec} › ${state}`)
    else
      for (const problem of problemsOf(
        description,
        new Set([...classes, ...base])
      ))
        rejected.push(`${spec} › ${state}: ${problem}`)
    const cell =
      classes.size > 0 ? [...classes].sort().map(code).join(" · ") : "—"
    lines.push(`| ${code(state)} | ${cell} | ${description} |`)
  }

  const composed = composedOf(ROOT, codePath, specOf)
  lines.push(
    "",
    `Collected from ${code(codePath)} and the \`lib/\` constants it imports. **Classes**: each class whose variants name the state, as written (\`dark:\` included); a class that stacks two states is listed under both. \`—\`: no class of its own — \`default\` is what the other states change.`
  )
  if (composed.length > 0)
    lines.push(
      "",
      `Composes ${composed.map(code).join(", ")} — ${composed.length > 1 ? "their states are listed in their own specs" : "its states are listed in its own spec"}.`
    )
  lines.push("", END)
  if (tail) lines.push("", tail)
  return lines.join("\n") + "\n"
}

/** Replace the section, which every spec has (lint-spec-sections checks it). */
function withSection(markdown: string, section: string): string {
  const start = markdown.indexOf(`\n${HEADING}\n`)
  if (start === -1) throw new Error(`no "${HEADING}" section`)
  const next = markdown.indexOf("\n## ", start + 1)
  return (
    markdown.slice(0, start + 1) + section + "\n" + markdown.slice(next + 1)
  )
}

function sectionOf(markdown: string): string {
  const start = markdown.indexOf(`\n${HEADING}\n`) + HEADING.length + 2
  const next = markdown.indexOf("\n## ", start)
  return markdown.slice(start, next === -1 ? undefined : next)
}

const codePathOf = codePathsOf(SPECS_DIR)
const specOf = new Map(
  [...codePathOf].map(([file, codePath]) => [codePath, basename(file, ".md")])
)

const stale: string[] = []
for (const [file, codePath] of codePathOf) {
  const path = resolve(SPECS_DIR, file)
  const spec = basename(file, ".md")
  if (ONLY.size > 0 && !ONLY.has(spec)) continue
  const current = readFileSync(path, "utf-8")
  const section = await sectionFor(spec, codePath, sectionOf(current), specOf)
  const next = await format(withSection(current, section), {
    ...(await resolveConfig(path)),
    filepath: path,
  })
  if (next === current) continue
  if (CHECK) stale.push(spec)
  else writeFileSync(path, next)
}

const failures: string[] = []
if (unclassified.size > 0)
  failures.push(
    `${unclassified.size} variant(s) in neither STATES nor LAYOUT — classify each one in scripts/build-spec-states.ts:\n` +
      [...unclassified].map((v) => `   - ${v}`).join("\n")
  )
if (undocumented.length > 0)
  failures.push(
    `${undocumented.length} state(s) the code draws with no description — write it in place of ${PLACEHOLDER}:\n` +
      undocumented.map((s) => `   - ${s}`).join("\n")
  )
if (rejected.length > 0)
  failures.push(
    `${rejected.length} description(s) the Classes column contradicts:\n` +
      rejected.map((s) => `   - ${s}`).join("\n")
  )
if (CHECK && stale.length > 0)
  failures.push(
    `${stale.length} spec(s) out of date with the classes of their code: ${stale.join(", ")}\n` +
      "   Run `npm run specs:states` and commit the result."
  )

if (failures.length > 0) {
  for (const failure of failures)
    console.error(`❌ build-spec-states: ${failure}`)
  process.exit(1)
}
console.log(
  CHECK
    ? "✅ build-spec-states: every spec's States section matches the code."
    : "✅ build-spec-states: States sections written."
)
