/**
 * Writes the code examples of the specs into site/generated/examples/, as
 * modules the documentation site renders live.
 *
 * The site shows each example running next to its source. Its source is the
 * spec: the example an agent copies is the one the site renders, never a
 * parallel fixture. Next.js has no equivalent of the Vite plugin the tests
 * read the specs through (tests/spec-examples.ts), so the examples are copied
 * here, as written, and checked like the other generated files:
 *
 * - every component spec's `## Code example` → `components/<Name>.tsx`;
 * - every pattern's `## Code example` → `patterns/<name>.tsx`; a pattern that
 *   exports a component taking props is mounted by the `render` of its eval
 *   task (evals/tasks.json), as the conformance harness mounts it;
 * - every complete module of a foundation (a tsx block that imports what it
 *   renders and exports it by default) → `foundations/<name>-<n>.tsx`, keyed
 *   by its rank in the file, so editing the text above it renames nothing.
 *
 * Each file opens with `"use client"`: the examples hold state and handlers,
 * and the site renders them in the browser. `index.ts` maps each name to a
 * loader, so a page loads its own example only. The copies are type-checked
 * with the site (npm run typecheck:site) and linted with the config a
 * consuming project runs (scripts/lint-site.ts).
 *
 *   npx tsx scripts/build-site-examples.ts [--check]
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { basename, dirname, join, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { format, resolveConfig } from "prettier"

import {
  foundationBlocks,
  isCompleteModule,
  specExample,
} from "../tests/spec-examples"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const CHECK = process.argv.includes("--check")
const OUT = resolve(ROOT, "site/generated/examples")
const SCRIPT = "scripts/build-site-examples.ts"

interface Task {
  gold: { pattern?: string; render?: string }
}
const tasks = (
  JSON.parse(readFileSync(resolve(ROOT, "evals/tasks.json"), "utf-8")) as {
    tasks: Task[]
  }
).tasks

/** The `render` the eval tasks mount a pattern's example with, if any. */
function patternRender(name: string): string | undefined {
  return tasks.find((t) => t.gold.pattern === name && t.gold.render)?.gold
    .render
}

function markdownFiles(dir: string): string[] {
  return readdirSync(resolve(ROOT, dir))
    .filter((f) => f.endsWith(".md"))
    .sort()
}

/** A module the site can render: the header, `"use client"`, then the code. */
function module(source: string, code: string): string {
  const body = code.replace(/^"use client"\n+/, "")
  return `// Generated by ${SCRIPT} from ${source} — do not edit by hand.\n"use client"\n\n${body}`
}

/** Generated files, by path relative to OUT. */
const files = new Map<string, string>()
const loaders: Record<"components" | "patterns" | "foundations", string[]> = {
  components: [],
  patterns: [],
  foundations: [],
}

for (const file of markdownFiles("specs/components")) {
  const name = basename(file, ".md")
  const source = `specs/components/${file}`
  const code = specExample(readFileSync(resolve(ROOT, source), "utf-8"))
  files.set(`components/${name}.tsx`, module(source, code))
  loaders.components.push(name)
}

for (const file of markdownFiles("specs/patterns")) {
  const name = basename(file, ".md")
  const source = `specs/patterns/${file}`
  let code = specExample(readFileSync(resolve(ROOT, source), "utf-8"))
  if (!/^export default /m.test(code)) {
    const render = patternRender(name)
    if (!render)
      throw new Error(
        `${source}: the example has no default export and no eval task gives it a "render"`
      )
    code = `${code}\nexport default function PatternPreview() {\n  return ${render}\n}\n`
  }
  files.set(`patterns/${name}.tsx`, module(source, code))
  loaders.patterns.push(name)
}

for (const file of markdownFiles("specs/foundations")) {
  const name = basename(file, ".md")
  const source = `specs/foundations/${file}`
  const blocks = foundationBlocks(
    readFileSync(resolve(ROOT, source), "utf-8"),
    source
  ).filter((block) => block.lang === "tsx" && isCompleteModule(block.code))
  blocks.forEach((block, i) => {
    const key = `${name}-${i + 1}`
    files.set(`foundations/${key}.tsx`, module(source, block.code))
    loaders.foundations.push(key)
  })
}

function loaderMap(kind: keyof typeof loaders): string {
  const entries = loaders[kind].map(
    (name) => `  ${JSON.stringify(name)}: () => import("./${kind}/${name}"),`
  )
  return `export const ${kind}: Loaders = {\n${entries.join("\n")}\n}\n`
}

files.set(
  "index.ts",
  [
    `// Generated by ${SCRIPT} — do not edit by hand.`,
    `import type { ComponentType } from "react"`,
    ``,
    `/** One loader per example, so a page loads its own example only. */`,
    `export type Loaders = Record<string, () => Promise<{ default: ComponentType }>>`,
    ``,
    `/** The \`## Code example\` of each component spec, by spec name. */`,
    loaderMap("components"),
    `/** The \`## Code example\` of each pattern, by file name. */`,
    loaderMap("patterns"),
    `/** The complete modules of each foundation: \`<file>-<rank>\`. */`,
    loaderMap("foundations"),
  ].join("\n")
)

/** Every file under OUT, relative to it. */
function existing(dir = OUT): string[] {
  if (!existsSync(dir)) return []
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name)
    return entry.isDirectory() ? existing(path) : [relative(OUT, path)]
  })
}

const stale: string[] = []
for (const [path, raw] of files) {
  const target = resolve(OUT, path)
  const next = await format(raw, {
    ...(await resolveConfig(target)),
    filepath: target,
  })
  const current = existsSync(target) ? readFileSync(target, "utf-8") : null
  if (next === current) continue
  if (CHECK) stale.push(path)
  else {
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, next)
  }
}
for (const path of existing()) {
  if (files.has(path)) continue
  if (CHECK) stale.push(`${path} (no longer generated)`)
  else rmSync(resolve(OUT, path))
}

if (CHECK && stale.length > 0) {
  console.error(
    `❌ build-site-examples: ${stale.length} file(s) of site/generated/examples out of date with the specs: ${stale.join(", ")}\n` +
      "   Run `npm run site:examples` and commit the result."
  )
  process.exit(1)
}
console.log(
  CHECK
    ? `✅ build-site-examples: the ${files.size - 1} examples match the specs.`
    : `✅ build-site-examples: ${files.size - 1} examples written.`
)
