/**
 * Writes the `## States` section of every component spec from the classes of
 * the component's code.
 *
 * Written by hand, the table had drifted: Button's hover claimed "90 %
 * opacity" where the code draws `hover:bg-primary/80`, Slider's ring was
 * "1px" where the code draws `--space-focus-ring-width`, ten overlays entered
 * with `fade-in` where the code has `fade-in-0`. The code now decides which
 * states a component draws and the classes that draw each one; people write
 * the descriptions, which are read back from the spec and kept.
 *
 * - Each class of the component's file, of the `@/lib/*` constants it
 *   imports and of the `*Variants` functions it calls from another component
 *   (scripts/lib/spec-classes.ts), goes under the state its variants name:
 *   `hover:`, `focus-visible:`, `data-open:`, `aria-invalid:`… (STATES, in
 *   scripts/lib/spec-states.ts). A class that stacks two states
 *   (`data-open:hover:`) is listed under both, as written. Layout variants
 *   (`dark:`, `sm:`, `data-[size=sm]:`, `*:`) name no state (LAYOUT). A
 *   variant in neither table fails the run, so a new one is classified, never
 *   dropped.
 * - A state the component never enters through a `*Variants` function it
 *   applies is declared, not listed: a hand-written line of the section,
 *   "Not entered through `buttonVariants`: `disabled` — why", kept like a
 *   description, drops the classes of that state that come through it. A
 *   declaration that names a state the function draws no class for fails the
 *   run.
 * - A row is kept from the spec by its state, with its description. A state
 *   the code draws and the spec does not describe gets `_To document._`, and
 *   the run fails until it is written. A row the code has no class for
 *   (`default`, `loading`) stays, with `—`.
 * - A description is rejected when the Classes column can contradict it: a
 *   percentage or a px value, or a class the component does not draw — the
 *   row's own classes and the component's stateless ones are the ones it may
 *   name. That is how Button's "90 %" was born.
 *
 *   npx tsx scripts/build-spec-states.ts [--check] [Spec…]
 *
 * Spec names (`Button Dialog`) limit the run to those specs.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { resolve, dirname, basename } from "node:path"
import { fileURLToPath } from "node:url"
import { format, resolveConfig } from "prettier"
import {
  appliedText,
  classResolver,
  codePathsOf,
  composedOf,
  composesLine,
  neverEntered,
  notEnteredOf,
  stringsOf,
  utilityOf,
  variantsAppliedBy,
  variantsOf,
  type NotEntered,
} from "./lib/spec-classes.js"
import { ORDER, statesOf, unclassified } from "./lib/spec-states.js"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const CHECK = process.argv.includes("--check")
const ONLY = new Set(process.argv.slice(2).filter((a) => !a.startsWith("--")))
const SPECS_DIR = resolve(ROOT, "specs/components")
const HEADING = "## States"
const START =
  "<!-- Generated by scripts/build-spec-states.ts from the component's classes. Only the descriptions are edited by hand; they are kept. -->"
const END = "<!-- End of the generated part. -->"
const PLACEHOLDER = "_To document._"

// ---------------------------------------------------------------------------
// Variants a Radix component never matches
// ---------------------------------------------------------------------------
/**
 * The variants a Radix component can never match. The radix-lyra style sheet is
 * written once for Radix and Base UI, so a class that waits for a Base UI
 * attribute (`data-popup-open`, `data-starting-style`, `data-ending-style`,
 * `data-instant`) comes along into a Radix component, where it draws nothing
 * and the States table lists it as if it did. A Radix tooltip never writes
 * `data-state="open"` (Base UI's `data-open`, bridged to it): it writes
 * `delayed-open` or `instant-open`, so a bare `data-open` never matches.
 */
const BASE_UI_ONLY =
  /^data-(?:popup-open|starting-style|ending-style|instant)$|^data-\[(?:starting-style|ending-style|instant)(?:=[^\]]*)?\]$/
const neverMatching = new Set<string>()

function neverMatchesOnRadix(
  variant: string,
  file: string,
  radix: boolean
): boolean {
  const v = variant
    .replace(/^(?:group|peer)-/, "")
    .replace(/\/[\w-]+$/, "")
    .replace(/^has-/, "")
  if (radix && BASE_UI_ONLY.test(v)) return true
  return /(?:^|\/)tooltip\.tsx$/.test(file) && v === "data-open"
}

// ---------------------------------------------------------------------------
// The classes of a component, by state
// ---------------------------------------------------------------------------
const cssOf = await classResolver(ROOT)

interface Classes {
  /** state → the classes that draw it, as written. */
  byState: Map<string, Set<string>>
  /** The classes with no state variant: the component at rest. */
  base: Set<string>
  /** `*Variants` function → the states its classes name, before any is declared not entered. */
  composedStates: Map<string, Set<string>>
}

async function classesOf(
  codePath: string,
  notEntered: NotEntered[]
): Promise<Classes> {
  const byState = new Map<string, Set<string>>()
  const base = new Set<string>()
  const composedStates = new Map<string, Set<string>>()
  const radix = /from\s+["'](?:radix-ui|@radix-ui\/)/.test(
    readFileSync(resolve(ROOT, codePath), "utf-8")
  )
  for (const { text, via } of await stringsOf(ROOT, codePath)) {
    const candidates = text.split(/\s+/).filter(Boolean)
    cssOf(candidates).forEach((css, i) => {
      if (!css) return
      const candidate = candidates[i]
      if (via) {
        const named = composedStates.get(via) ?? new Set()
        for (const v of variantsOf(candidate))
          for (const state of statesOf(v, codePath)) named.add(state)
        composedStates.set(via, named)
        if (neverEntered(candidate, via, notEntered, codePath)) return
      }
      if (
        variantsOf(candidate).some((v) =>
          neverMatchesOnRadix(v, codePath, radix)
        )
      )
        neverMatching.add(`${candidate} (${codePath})`)
      const states = new Set(
        variantsOf(candidate).flatMap((v) => statesOf(v, codePath))
      )
      if (states.size === 0) base.add(candidate)
      for (const state of states) {
        const set = byState.get(state) ?? new Set()
        set.add(candidate)
        byState.set(state, set)
      }
    })
  }
  return { byState, base, composedStates }
}

// ---------------------------------------------------------------------------
// What the spec already says
// ---------------------------------------------------------------------------
const code = (s: string) => `\`${s.replace(/\|/g, "\\|")}\``
const cells = (line: string) =>
  line
    .trim()
    .replace(/^\||\|$/g, "")
    .split(/(?<!\\)\|/)
    .map((c) => c.trim())
/** A row's key: its state, without backticks, in lower case. */
const keyOf = (cell: string) => cell.replace(/`/g, "").trim().toLowerCase()

interface Existing {
  /** state → description, in the order written. */
  rows: Map<string, string>
  /** What follows the generated part, kept as written. */
  tail: string
}

function readExisting(section: string, spec: string): Existing {
  const generated = section.includes(END)
  const body = generated ? section.split(END)[0] : section
  const tail = generated ? section.split(END)[1].trim() : ""
  const lines = body.split("\n")
  const at = lines.findIndex((l) => l.startsWith("|"))
  const rows = new Map<string, string>()
  if (at === -1) return { rows, tail }
  const header = cells(lines[at]).map((h) => h.toLowerCase())
  const desc = header.findIndex((h) =>
    ["description", "visual behavior"].includes(h)
  )
  if (desc === -1)
    throw new Error(`${spec}: the States table has no Description column`)
  for (const line of lines.slice(at + 2)) {
    if (!line.startsWith("|")) break
    const c = cells(line)
    const key = keyOf(c[0])
    const written = c[desc] ?? ""
    const before = rows.get(key)
    if (before !== undefined && before !== PLACEHOLDER)
      throw new Error(`${spec}: the States table has two "${key}" rows`)
    rows.set(key, written)
  }
  if (!generated) {
    const rest = lines
      .slice(at + 2)
      .filter((l) => !l.startsWith("|"))
      .join("\n")
      .trim()
    if (rest) throw new Error(`${spec}: prose after the States table`)
  }
  return { rows, tail }
}

// ---------------------------------------------------------------------------
// Descriptions the Classes column contradicts
// ---------------------------------------------------------------------------
const COLOR_NAMES = new Set(
  [
    ...readFileSync(resolve(ROOT, "styles/globals.css"), "utf-8").matchAll(
      /--color-([a-z0-9-]+):/g
    ),
  ].map(([, name]) => name)
)
const PX_OR_PERCENT = /\d\s*(?:%|px\b)/

/** Why a description cannot stand next to the classes it may name; empty when it can. */
function problemsOf(description: string, allowed: Set<string>): string[] {
  const problems: string[] = []
  const utilities = new Set([...allowed].map(utilityOf))
  if (PX_OR_PERCENT.test(description.replace(/`[^`]*`/g, " ")))
    problems.push(
      "states a percentage or a px value: name the class or the token"
    )
  for (const [, span] of description.matchAll(/`([^`]+)`/g)) {
    for (const word of span.split(/\s+/).filter(Boolean)) {
      const isClass =
        /[-:/[(]/.test(word) &&
        !word.startsWith("--") &&
        !COLOR_NAMES.has(word) &&
        cssOf([word])[0] !== null
      if (!isClass) {
        if (!word.startsWith("--") && PX_OR_PERCENT.test(word))
          problems.push(
            `\`${word}\` is a raw value: name the class or the token`
          )
        continue
      }
      if (!allowed.has(word) && !utilities.has(word))
        problems.push(`names \`${word}\`, which the component does not draw`)
    }
  }
  return problems
}

// ---------------------------------------------------------------------------
// Section
// ---------------------------------------------------------------------------
const rejected: string[] = []
const undocumented: string[] = []
const misdeclared: string[] = []

async function sectionFor(
  spec: string,
  codePath: string,
  section: string,
  specOf: Map<string, string>
): Promise<string> {
  const notEntered = notEnteredOf(section.split(END)[0])
  const { byState, base, composedStates } = await classesOf(
    codePath,
    notEntered
  )
  const { rows: written, tail } = readExisting(section, spec)
  for (const { fn, states } of notEntered) {
    const named = composedStates.get(fn)
    if (!named) misdeclared.push(`${spec}: ${code(codePath)} applies no ${fn}`)
    else if (states.length === 0)
      misdeclared.push(`${spec}: the ${fn} declaration names no state`)
    for (const state of states)
      if (named && !named.has(state))
        misdeclared.push(`${spec}: ${fn} draws no \`${state}\` class`)
  }

  const drawn = (state: string) => byState.get(state) ?? new Set<string>()
  const states = [
    ...ORDER.filter((s) => s === "default" || byState.has(s) || written.has(s)),
    ...[...byState.keys()].filter((s) => !ORDER.includes(s)),
    ...[...written.keys()].filter((s) => !ORDER.includes(s) && !byState.has(s)),
  ]

  const lines = [
    HEADING,
    "",
    START,
    "",
    "| State | Classes | Description |",
    "|---|---|---|",
  ]
  for (const state of states) {
    const classes = drawn(state)
    const description = written.get(state) || PLACEHOLDER
    if (description === PLACEHOLDER) undocumented.push(`${spec} › ${state}`)
    else
      for (const problem of problemsOf(
        description,
        new Set([...classes, ...base])
      ))
        rejected.push(`${spec} › ${state}: ${problem}`)
    const cell =
      classes.size > 0 ? [...classes].sort().map(code).join(" · ") : "—"
    lines.push(`| ${code(state)} | ${cell} | ${description} |`)
  }

  const applied = variantsAppliedBy(ROOT, codePath)
  const composes = composesLine(composedOf(ROOT, codePath, specOf), "states")
  lines.push(
    "",
    `Collected from ${code(codePath)}${applied.size > 0 ? `, the \`lib/\` constants it imports and ${appliedText(applied)}` : " and the `lib/` constants it imports"}. **Classes**: each class whose variants name the state, as written (\`dark:\` included); a class that stacks two states is listed under both. \`—\`: no class of its own — \`default\` is what the other states change.`
  )
  for (const { line } of notEntered) lines.push("", line)
  if (composes) lines.push("", composes)
  lines.push("", END)
  if (tail) lines.push("", tail)
  return lines.join("\n") + "\n"
}

/** Replace the section, which every spec has (lint-spec-sections checks it). */
function withSection(markdown: string, section: string): string {
  const start = markdown.indexOf(`\n${HEADING}\n`)
  if (start === -1) throw new Error(`no "${HEADING}" section`)
  const next = markdown.indexOf("\n## ", start + 1)
  return (
    markdown.slice(0, start + 1) + section + "\n" + markdown.slice(next + 1)
  )
}

function sectionOf(markdown: string): string {
  const start = markdown.indexOf(`\n${HEADING}\n`) + HEADING.length + 2
  const next = markdown.indexOf("\n## ", start)
  return markdown.slice(start, next === -1 ? undefined : next)
}

const codePathOf = codePathsOf(SPECS_DIR)
const specOf = new Map(
  [...codePathOf].map(([file, codePath]) => [codePath, basename(file, ".md")])
)

const stale: string[] = []
for (const [file, codePath] of codePathOf) {
  const path = resolve(SPECS_DIR, file)
  const spec = basename(file, ".md")
  if (ONLY.size > 0 && !ONLY.has(spec)) continue
  const current = readFileSync(path, "utf-8")
  const section = await sectionFor(spec, codePath, sectionOf(current), specOf)
  const next = await format(withSection(current, section), {
    ...(await resolveConfig(path)),
    filepath: path,
  })
  if (next === current) continue
  if (CHECK) stale.push(spec)
  else writeFileSync(path, next)
}

const failures: string[] = []
if (unclassified.size > 0)
  failures.push(
    `${unclassified.size} variant(s) in neither STATES nor LAYOUT — classify each one in scripts/lib/spec-states.ts:\n` +
      [...unclassified].map((v) => `   - ${v}`).join("\n")
  )
if (neverMatching.size > 0)
  failures.push(
    `${neverMatching.size} class(es) a Radix component can never match — a Base UI attribute, or a bare data-open on a tooltip (it writes delayed-open or instant-open). Map it to the Radix attribute, or out, in shadcn-upstream.json:\n` +
      [...neverMatching].map((c) => `   - ${c}`).join("\n")
  )
if (undocumented.length > 0)
  failures.push(
    `${undocumented.length} state(s) the code draws with no description — write it in place of ${PLACEHOLDER}:\n` +
      undocumented.map((s) => `   - ${s}`).join("\n")
  )
if (rejected.length > 0)
  failures.push(
    `${rejected.length} description(s) the Classes column contradicts:\n` +
      rejected.map((s) => `   - ${s}`).join("\n")
  )
if (misdeclared.length > 0)
  failures.push(
    `${misdeclared.length} "Not entered through" declaration(s) the code does not bear out — remove the state, or the line:\n` +
      misdeclared.map((s) => `   - ${s}`).join("\n")
  )
if (CHECK && stale.length > 0)
  failures.push(
    `${stale.length} spec(s) out of date with the classes of their code: ${stale.join(", ")}\n` +
      "   Run `npm run specs:states` and commit the result."
  )

if (failures.length > 0) {
  for (const failure of failures)
    console.error(`❌ build-spec-states: ${failure}`)
  process.exit(1)
}
console.log(
  CHECK
    ? "✅ build-spec-states: every spec's States section matches the code."
    : "✅ build-spec-states: States sections written."
)
