import type { Story } from "@/site/playground/types"

/**
 * The hand-written playgrounds, by spec name: every component that is not in
 * AUTO (site/playground/auto.ts) has one. A page loads its own only.
 */
export const SCENARIOS: Record<string, () => Promise<{ default: Story }>> = {
  Accordion: () => import("./Accordion"),
  Alert: () => import("./Alert"),
  AlertDialog: () => import("./AlertDialog"),
  AspectRatio: () => import("./AspectRatio"),
  Attachment: () => import("./Attachment"),
  Avatar: () => import("./Avatar"),
  Breadcrumb: () => import("./Breadcrumb"),
  Bubble: () => import("./Bubble"),
  ButtonGroup: () => import("./ButtonGroup"),
  Calendar: () => import("./Calendar"),
  Card: () => import("./Card"),
  Carousel: () => import("./Carousel"),
  Chart: () => import("./Chart"),
  Collapsible: () => import("./Collapsible"),
  Combobox: () => import("./Combobox"),
  Command: () => import("./Command"),
  ContextMenu: () => import("./ContextMenu"),
  Dialog: () => import("./Dialog"),
  Direction: () => import("./Direction"),
  Drawer: () => import("./Drawer"),
  DropdownMenu: () => import("./DropdownMenu"),
  Empty: () => import("./Empty"),
  Field: () => import("./Field"),
  HoverCard: () => import("./HoverCard"),
  InputGroup: () => import("./InputGroup"),
  InputOtp: () => import("./InputOtp"),
  Item: () => import("./Item"),
  Marker: () => import("./Marker"),
  Menubar: () => import("./Menubar"),
  Message: () => import("./Message"),
  MessageScroller: () => import("./MessageScroller"),
  NativeSelect: () => import("./NativeSelect"),
  NavigationMenu: () => import("./NavigationMenu"),
  Pagination: () => import("./Pagination"),
  Popover: () => import("./Popover"),
  Questionnaire: () => import("./Questionnaire"),
  RadioGroup: () => import("./RadioGroup"),
  Resizable: () => import("./Resizable"),
  ScrollArea: () => import("./ScrollArea"),
  Select: () => import("./Select"),
  Sheet: () => import("./Sheet"),
  Sidebar: () => import("./Sidebar"),
  Slider: () => import("./Slider"),
  Sonner: () => import("./Sonner"),
  Table: () => import("./Table"),
  Tabs: () => import("./Tabs"),
  ToggleGroup: () => import("./ToggleGroup"),
  Tooltip: () => import("./Tooltip"),
}
